src/components/common/item/CourseItem.tsx, src/components/common/item/CrewItem.tsx, src/components/common/item/ReviewItem.tsx, src/components/common/item/styled.ts, src/components/course/CourseList.styled.ts, src/components/course/CourseList.tsx, src/components/crew/CrewList.styled.ts, src/components/crew/CrewList.tsx, src/components/review/ReviewList.styled.ts, src/components/review/ReviewList.tsx
closed #10 
list 컴포넌트 높이 설정 및 item 컴포넌트 클릭 이벤트 설정
=> Feat: list 컴포넌트 높이 설정 및 item 컴포넌트 클릭 이벤트 설정

src/components/common/header/Header.tsx, src/pages/community/Community.tsx
#14 
커뮤니티 페이지 스크롤 위치에 따른 카테고리바 활성화 기능 설정
=> Feat: 커뮤니티 페이지 스크롤 위치에 따른 카테고리바 활성화 기능 설정

src/pages/community/Community.tsx
=> Design: 커뮤니티 페이지 padding 조정

src/components/common/header/Header.tsx, src/components/course/courseInfo/DetailCourseList.styled.ts, src/components/course/courseInfo/DetailCourseList.tsx, src/components/course/courseInfo/RoadView.styled.ts, src/components/course/courseInfo/RoadView.tsx, src/pages/course/CourseInfo.styled.ts, src/pages/course/CourseInfo.tsx
closed #20   
course info 페이지 UI 구현 마무리 및 상세코스 컴포넌트 구현
카테고리바 연결
| 상세 코스 리스트 컴포넌트 |
| -- |
|<img src="https://github.com/user-attachments/assets/1dd53805-5f82-4d73-be54-cab59be17d40" width="300"/>|
| 카테고리바-약도 | 카테고리바-상세 코스 | 카테고리바-리뷰 |
|--|--|--|
|<img src="https://github.com/user-attachments/assets/86aa30ec-1729-43a4-906b-0cd1730d3ce8" width="300"/>|<img src="https://github.com/user-attachments/assets/e036cc27-a107-4339-b29d-8f6c4988ba69" width="300"/>|<img src="https://github.com/user-attachments/assets/2c10e3c5-399f-4d2d-b036-eaf2c9a4a5cf" width="300"/>|
=> Feat: course info 페이지 UI 구현 마무리 및 상세코스 컴포넌트 구현

src/apis/account/AccountApi.tsx, src/apis/mypage/MypageApi.tsx, src/components/common/footer/Footer.tsx, src/components/mypage/ButtonGroup.tsx, src/components/mypage/DeleteAccountModal.tsx, src/components/mypage/UserInfo.tsx, src/router.tsx
closed  #40 
회원탈퇴, 로그아웃, 유저정보 api 연동 완료했습니다 ~!
=> feat: 회원탈퇴, 로그아웃, 유저정보 api 연동

src/apis/community/CommunityApi.tsx, src/apis/community/CrewApi.tsx, src/apis/community/ReviewApi.tsx, src/apis/mypage/MypageApi.tsx, src/components/common/item/CrewItem.tsx, src/components/common/list/CrewList.tsx, src/components/common/list/ReviewList.tsx, src/components/community/CommunityCrew.tsx, src/components/community/CommunityReview.tsx, src/components/community/crew/CrewEditForm.tsx, src/components/community/crew/CrewForm.tsx, src/components/community/crew/styled.ts, src/components/community/read/ButtonGroup.tsx, src/components/community/read/PostCreateInfo.tsx, src/components/community/read/styled.ts, src/hooks/useImageUpload.ts, src/pages/community/crew/CrewEdit.tsx, src/pages/community/crew/CrewRead.tsx, src/pages/community/crew/CrewWrite.tsx, src/pages/community/review/ReviewRead.tsx, src/pages/signup/SignUp.tsx
closed #42 
커뮤니티 리뷰 글 작성, 수정 제외한 모든 api 연동 완료했습니다!
=> feat: 커뮤니티 api 연동

src/apis/community/CrewApi.tsx
커뮤니티 글 수정 이미지 캐싱할 때 CORS 헤더 누락 오류 해결 
커뮤니티 글 수정 이미지 캐싱할 때 CORS 헤더 누락 오류 해결했어요!!! 완조니 이제 끝남 .
=> Fix: 글 수정 이미지 캐싱할 때 CORS 헤더 누락 오류 해결 

package-lock.json, src/apis/account/AccountApi.tsx, src/apis/course/courseList/CourseListApi.tsx, src/components/common/list/CourseList.tsx, src/components/common/list/ReviewList.tsx, src/components/community/CommunityReview.tsx, src/components/course/courseList/CourseListComp.tsx, src/components/mypage/LikedList.tsx, src/components/mypage/MyReviewList.tsx, src/components/mypage/ScrapedList.tsx, src/router.tsx, src/style/global.ts
closed #49 
1. 코스리스트 페이지 코스 리스트 연동 완료했어요
2. 코스리스트 컴포넌트 클릭 시 코스 인포에 course_id 달아서 넘어갈 수 있게 설정했습니다.
=> feat: 코스리스트 코스 목록 api 연동

src/apis/account/AccountApi.tsx, src/apis/community/CrewApi.tsx, src/apis/course/courseInfo/StampAuthenticateApi.tsx, src/components/common/item/styled.ts, src/components/course/courseInfo/DetailCourseList.tsx, src/pages/community/crew/CrewEdit.tsx, src/pages/login/Login.tsx
closed #52 
코스인포 상세코스 조회 스탬프 받기 api 연동 완료했습니다 ~
| 코스인포 - 상세코스 연동| 스탬프 인증 받기 연동 |
|--|--|
| <img width="390" alt="스크린샷 2025-05-02 오전 12 21 58" src="https://github.com/user-attachments/assets/5a09f727-15bb-4818-9917-7b3beceea8e1" /> | <img width="402" alt="스크린샷 2025-05-02 오전 12 21 31" src="https://github.com/user-attachments/assets/60a20ad7-2efc-485e-ab67-d49669e0710e" /> |
=> feat: 코스인포 상세코스 조회 스탬프 받기 api 연동

src/components/course/courseList/MountainBanner.styled.ts, src/components/course/courseList/MountainBanner.tsx
closed #62 
산 배너 고정 높이 때문에 발생하는 스타일 오류 해결 완료
| 산 배너 | 산 배너 |
|--|--|
| <img width="350" alt="스크린샷 2025-05-02 오후 3 11 27" src="https://github.com/user-attachments/assets/caea4be8-1211-443f-a041-1d48880a0983" /> | <img width="350" alt="스크린샷 2025-05-02 오후 3 11 11" src="https://github.com/user-attachments/assets/247124b1-d329-4ece-950b-2042d2cd21b6" /> |
=> fix: 산 배너 스타일 오류 해결

src/apis/community/CrewApi.tsx, src/apis/rank/RankApi.tsx, src/components/common/list/CourseList.tsx, src/components/community/review/ReviewEditForm.tsx, src/components/rank/RankList.tsx, src/components/rank/Top3.tsx, src/hooks/useNaverMap.ts, src/pages/community/review/ReviewEdit.tsx
closed #65   
리뷰 삭제 시 경로 이동 오류 해결, 콘솔 로그 주석처리
=> fix: 리뷰 삭제 시 경로 이동 오류 해결

src/components/home/Search.tsx
=> Fix: search.tsx 컴포넌트 배포 중 오류 해결

index.html
#74 
실시간 도시데이터 Mixed content 
html파일 head에 추가
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
참고: https://wellsw.tistory.com/34
=> Fix: 실시간 도시데이터 Mixed content 에러 해결

src/components/course/courseInfo/CourseData.tsx
#77 
json 파일 불러오는 다양한 방법 주석으로 추가
=> Comment: json 파일 불러오는 다양한 방법 주석으로 추가

src/components/course/courseInfo/CourseData.tsx, src/components/course/courseInfo/DetailCourseList.tsx, src/components/course/courseInfo/SketchMap.tsx
#76 
동적 import 방식 수정 ➡️ Vite의 import.meta.glob 활용
=> Fix: 동적 import 방식 수정 (Vite의 import.meta.glob 활용)

src/apis/home/WeatherApi.tsx, src/components/home/Weather.tsx
closed #73 
실시간 도시데이터 (날씨) 백엔드 api 연동으로 변경 구현
(프론트에서 자체적으로 api 호출 ➡️ 서울시 열린데이터광장에서 http만 제공 해서 프로토콜 문제 발생 ➡️ 백엔드 api로 연동)
=> Fix: 실시간 도시데이터 (날씨) 백엔드 api 연동으로 변경 구현

src/apis/community/CrewApi.tsx
=> Fix: 커뮤니티 - 크루 글 리스트 최신순으로 보이게 설정

src/components/common/card/CardList.tsx
=> Fix: 리뷰 좋아요 클릭 연동

src/components/common/card/CardList.tsx
=> Fix: 리뷰 카드 자세히보기 navigate 함수 추가

src/components/common/auth/ProtectedRoute.tsx, src/pages/error/NotMember.tsx, src/router.tsx
closed #86 
사용자 아닌 경우 접근 제한 페이지 만들고, token값이 스토리지에 없는 경우 /not-member로 이동하게 설정했습니다~!
| not-member 페이지 | 
|--|
| <img width="300" alt="not-member" src="https://github.com/user-attachments/assets/43871c5e-80fe-4c4b-867a-1a692d83e4ee" /> |
=> feat 사용자 아닌 경우 접근 제한 페이지

src/components/mypage/Stamp.styled.ts
#89 
스탬프 svg 이미지 깨짐 오류 해결 1차 시도
=> Fix: 스탬프 svg 이미지 깨짐 오류 해결 1차 시도

src/style/global.ts
사파리 font 깨짐 해결 (가중치 범위 조정, 폰트 합성 비활성화)
=> UX: 사파리 font 깨짐 해결 (가중치 범위 조정, 폰트 합성 비활성화)

src/components/mypage/Stamp.styled.ts
89 fix safari 브라우저에서 이미지 오류 해결
=> 89 fix safari 브라우저에서 이미지 오류 해결

index.html
=> Fix: seo 이미지 안뜨는 오류 수정

index.html
=> Fix: 공유하기 모달 컨텐츠 왼쪽 쏠림 현상 해결

src/components/course/courseInfo/CourseData.tsx, src/components/course/courseInfo/DetailCourseList.tsx
=> fix: 코스인포 페이지 오류 해결

src/components/course/courseInfo/CourseData.tsx, src/components/course/courseInfo/DetailCourseList.tsx
=> fix 코스인포 페이지 오류 해결

src/components/common/header/Header.tsx, src/pages/course/CourseInfo.tsx
=> Chore: 코스 인포 페이지 카테고리 스크롤 수정

src/pages/course/CourseInfo.tsx
=> Test: 코스 인포 페이지 디버깅을 위한 상세코스 코드 주석처리

src/components/course/courseInfo/DetailCourseList.tsx, src/components/course/courseInfo/RoadView.tsx, src/pages/course/CourseInfo.tsx
=> fix: 코스인포 페이지 오류 해결 시도중

src/components/common/card/styled.ts, src/components/course/courseInfo/CourseReview.tsx, src/components/course/courseList/MountainReview.tsx
피그마와 다른 스타일 + padding 설정 안된 부분(리뷰작성하기 버튼)이 있어서 수정했습니다~!
| 코스리스트 리뷰 | 코스인포 리뷰 | 코스인포 리뷰 없는 경우|
|--|--|--|
|<img width="320" alt="스크린샷 2025-05-10 오전 12 48 32" src="https://github.com/user-attachments/assets/61b60bae-35b1-4707-9d4f-b94e3e168836" />| <img width="320" alt="스크린샷 2025-05-10 오전 12 48 46" src="https://github.com/user-attachments/assets/9b5cc66c-5046-4a1a-a839-dc3516eea29e" /> | <img width="320" alt="스크린샷 2025-05-10 오전 12 49 02" src="https://github.com/user-attachments/assets/146a3901-c681-48e4-892f-8991dc9c6045" />|
=> Design: courseInfo 페이지 스타일 재설정

src/components/common/card/styled.ts, src/components/course/courseList/CourseListComp.styled.ts, src/components/course/courseList/MountainReview.tsx, src/pages/course/CourseList.tsx
=> Fix: 코스 리뷰 컴포넌트 스타일 오류 수정

src/components/course/courseList/MountainReview.tsx, src/pages/course/CourseList.tsx
=> Design: 산 리뷰 데이터 없는 경우 width 스타일 제거

src/pages/community/crew/CrewRead.tsx, src/pages/community/crew/CrewWrite.tsx, src/pages/community/review/ReviewRead.tsx, src/pages/community/review/ReviewWrite.tsx
=> Fix: back 버튼 navigate(-1)로 수정

src/components/community/read/styled.ts, src/pages/community/crew/CrewRead.tsx, src/pages/community/review/ReviewRead.tsx
1. 크루, 리뷰 조회 줄바꿈 설정
2. 크루, 리뷰 내글 조회 버튼 위치 스타일 오류 수정
3. 크루, 리뷰 조회 padding-bottom 레이아웃이 없어서 3rem 설정했습니다~!
| 커뮤니티 글 조회 줄바꿈 설정 | 커뮤니티 내 글 조회 버튼 위치 오류 수정 | 커뮤니티 글 조회 아래 padding 설정 |
|--|--|--|
|<img width="300" alt="스크린샷 2025-05-15 오후 11 46 43" src="https://github.com/user-attachments/assets/9a8a5037-d56b-4afb-9150-e30d29d3dfcc" />|<img width="300" alt="스크린샷 2025-05-15 오후 11 47 42" src="https://github.com/user-attachments/assets/9166b774-e224-4b6b-9290-6f25e719c3e6" />|<img width="300" alt="스크린샷 2025-05-15 오후 11 46 56" src="https://github.com/user-attachments/assets/7fc391eb-8680-43ac-8b8e-98560e340b53" />|
=> fix 커뮤니티 스타일 오류 수정
